# Generated by Django 3.2.23 on 2024-03-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dish_photos'),
        ),
    ]
