# Generated by Django 3.2.23 on 2024-03-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dish_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='count',
        ),
    ]
